//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import followIfLoginRedirect from './components/api-authorization/followIfLoginRedirect';

export class PersonalityTestClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    getQuestionsAndAnswers(): Promise<Question[]> {
        let url_ = this.baseUrl + "/api/PersonalityTest";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetQuestionsAndAnswers(_response);
        });
    }

    protected processGetQuestionsAndAnswers(response: Response): Promise<Question[]> {
        followIfLoginRedirect(response);
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(Question.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Question[]>(null as any);
    }

    submitTestAnswers(command: SubmitTestGetResultQuery): Promise<PersonalityTestResult> {
        let url_ = this.baseUrl + "/api/PersonalityTest";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(command);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSubmitTestAnswers(_response);
        });
    }

    protected processSubmitTestAnswers(response: Response): Promise<PersonalityTestResult> {
        followIfLoginRedirect(response);
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = PersonalityTestResult.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<PersonalityTestResult>(null as any);
    }
}

export class Question implements IQuestion {
    id?: number;
    text?: string | undefined;
    answers?: Answer[];

    constructor(data?: IQuestion) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.text = _data["text"];
            if (Array.isArray(_data["answers"])) {
                this.answers = [] as any;
                for (let item of _data["answers"])
                    this.answers!.push(Answer.fromJS(item));
            }
        }
    }

    static fromJS(data: any): Question {
        data = typeof data === 'object' ? data : {};
        let result = new Question();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["text"] = this.text;
        if (Array.isArray(this.answers)) {
            data["answers"] = [];
            for (let item of this.answers)
                data["answers"].push(item.toJSON());
        }
        return data;
    }
}

export interface IQuestion {
    id?: number;
    text?: string | undefined;
    answers?: Answer[];
}

export class Answer implements IAnswer {
    id?: number;
    questionId?: number;
    answerText?: string | undefined;

    constructor(data?: IAnswer) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.questionId = _data["questionId"];
            this.answerText = _data["answerText"];
        }
    }

    static fromJS(data: any): Answer {
        data = typeof data === 'object' ? data : {};
        let result = new Answer();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["questionId"] = this.questionId;
        data["answerText"] = this.answerText;
        return data;
    }
}

export interface IAnswer {
    id?: number;
    questionId?: number;
    answerText?: string | undefined;
}

export class PersonalityTestResult implements IPersonalityTestResult {
    id?: number;
    personalityTrait?: string | undefined;
    testTakenOn?: Date;

    constructor(data?: IPersonalityTestResult) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.personalityTrait = _data["personalityTrait"];
            this.testTakenOn = _data["testTakenOn"] ? new Date(_data["testTakenOn"].toString()) : <any>undefined;
        }
    }

    static fromJS(data: any): PersonalityTestResult {
        data = typeof data === 'object' ? data : {};
        let result = new PersonalityTestResult();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["personalityTrait"] = this.personalityTrait;
        data["testTakenOn"] = this.testTakenOn ? this.testTakenOn.toISOString() : <any>undefined;
        return data;
    }
}

export interface IPersonalityTestResult {
    id?: number;
    personalityTrait?: string | undefined;
    testTakenOn?: Date;
}

export class SubmitTestGetResultQuery implements ISubmitTestGetResultQuery {
    userAnswers?: UserAnswer[];

    constructor(data?: ISubmitTestGetResultQuery) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["userAnswers"])) {
                this.userAnswers = [] as any;
                for (let item of _data["userAnswers"])
                    this.userAnswers!.push(UserAnswer.fromJS(item));
            }
        }
    }

    static fromJS(data: any): SubmitTestGetResultQuery {
        data = typeof data === 'object' ? data : {};
        let result = new SubmitTestGetResultQuery();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.userAnswers)) {
            data["userAnswers"] = [];
            for (let item of this.userAnswers)
                data["userAnswers"].push(item.toJSON());
        }
        return data;
    }
}

export interface ISubmitTestGetResultQuery {
    userAnswers?: UserAnswer[];
}

export class UserAnswer implements IUserAnswer {
    id?: number;
    questionId?: number;
    answer?: Answer | undefined;

    constructor(data?: IUserAnswer) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.questionId = _data["questionId"];
            this.answer = _data["answer"] ? Answer.fromJS(_data["answer"]) : <any>undefined;
        }
    }

    static fromJS(data: any): UserAnswer {
        data = typeof data === 'object' ? data : {};
        let result = new UserAnswer();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["questionId"] = this.questionId;
        data["answer"] = this.answer ? this.answer.toJSON() : <any>undefined;
        return data;
    }
}

export interface IUserAnswer {
    id?: number;
    questionId?: number;
    answer?: Answer | undefined;
}

export class SwaggerException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new SwaggerException(message, status, response, headers, null);
}